### ISSUE TITLE
Need help with usage

### ISSUE THREAD

**Issue by dink10** [robinjoseph08/go-pg-migrations#19]
I try to use your lib, took code from example and it doesn't work. 

When I do go run cmd/migrate/*.go create create_users_table it works fine. After inserting code into `Exec` I do migrate and in my db 2 tables for migrations were appeared

```
go run cmd/migrate/*.go create create_users_table 
Creating database/migrations/20200128144423_create_users_table.go...
```

```
go run cmd/migrate/*.go migrate                  
Migrations already up to date
```

```
go run cmd/migrate/*.go rollback                 
No migrations have been run yet

```
But main table isn't present nowhere

**Comment by dink10** [comment]
Oh, now I see

It creates file by default in folder ./database/migrations and after that try to find that file in cmd/migrate/

**Comment by robinjoseph08** [comment]
Hey @dink10,

There actually isn't a default that is defined in this package. It's the required second argument to `Run`, so `./database/migrations` is the path that you passed into it (probably in `cmd/migrate/main.go`, but it could be elsewhere). Instead of passing in `./database/migrations`, you should pass in `cmd/migrate`. This value should be the path that you're migrations package is residing in. You can see how in [the example](https://github.com/robinjoseph08/go-pg-migrations/blob/cff956cb9f07b40516d26d5ecdbb89efb799144e/example/main.go#L11), it passes in `example` since that's the directory where `main.go` resides.

You can then fix your current setup by moving `database/migrations/20200128144423_create_users_table.go` into `cmd/migrate`. Then `go run cmd/migrate/*.go migrate` should work correctly.

Hopefully that clears things up! Let me know if you were able to get it working.

**Comment by dink10** [comment]
Yes, but if I use predefined folder it doesn't work, only if  all files located together

**Comment by dink10** [comment]
You pass derectory and never use that 

https://github.com/robinjoseph08/go-pg-migrations/blob/master/migrate.go#L25

`func migrate(db *pg.DB, directory string) error {`

That's why it doesn't work for me

**Comment by robinjoseph08** [comment]
Ah you're right that I pass in `directory` into `migrate` and don't use it, but the reason it's not used is because, as you mentioned, it assumes all the migration files are in the same package. When they are in the same package, they're all run in `init` functions and are registered so that other commands like migrate and rollback can use them. This is intentional and expected.

The reason it's like this is because it's non-trivial for a Go package to dynamically load another another Go file/package (as far as I'm aware of). So, if it's not going to load the migration files dynamically, it needs all of the migrations to be defined in the same package as the `main.go` so that it can pick up on the migrations automatically. The only thing that the `directory` variable is used for is for migration creation (so that it can write the file in the right location), so a change could be made to remove the passing of `directory` into `migrate`, though it is an internal function that wouldn't affect the external API.

If you want your migrations to live in `database/migrations`, then you'll have to move `cmd/migrate/main.go` to `database/migrations` as well. Unfortunately, this package requires them to live together. If you have a recommendation of how to dynamically load the migration files, I'd love to hear about it!

**Comment by robinjoseph08** [comment]
@dink10 I'm going to close this issue for now, but if you still need help, just let me know!
