### ISSUE TITLE
Do not require postgres connection on create

### ISSUE THREAD

**Issue by fizyk** [robinjoseph08/go-pg-migrations#21]
Right now creating migration files requires postgresql connection even if it's not used during the process

There's also no possibility to make custom wrapper, since create function is private and can't be imported.

It would help a lot if any one of these two were possible

**Comment by robinjoseph08** [comment]
Hey @fizyk,

That's a great point! Creating the file shouldn't require a connection. That should also be a pretty straightforward change as well. I'll try to get to it this weekend, but I would also accept a PR if you'd like to contribute! If you do plan on giving it a shot, let me know so we both don't do the work :sweat_smile:

As for the create function, this was intentionally made private to have greater control over the internal API. Now that this package is relatively stable, I would be more open to making it public, but if there was a compelling enough reason. Since it seems like your issue can be solved in another manner, I favor that solution instead of making it public.

**Comment by fizyk** [comment]
@robinjoseph08 sorry for my late response. I was hoarding notification email in a hope that I'll find a bit of time to work on it sooner rather than later, but haven't found the time to sit on it, not sure when I will
