### ISSUE TITLE
Migrate and Rollback takes in directory but doesn't use it

### ISSUE THREAD

**Issue by ernsheong** [robinjoseph08/go-pg-migrations#24]
See:
https://github.com/robinjoseph08/go-pg-migrations/blob/master/migrate.go#L25
https://github.com/robinjoseph08/go-pg-migrations/blob/master/rollback.go#L10

`directory` is passed in, but not used at all, hence migration and rollbacks don't work when migration is run from a separate directory?

**Comment by robinjoseph08** [comment]
Hey @ernsheong,

You're right that it's passed into these functions but doesn't use them. I should remove it as a function argument because it causes some confusion. The reason why it doesn't use it is explained [in this comment](https://github.com/robinjoseph08/go-pg-migrations/issues/19#issuecomment-579466036). All of the migrations are expected to be registered with `migrations.Register` in `init` functions, as demonstrated in [the example directory](https://github.com/robinjoseph08/go-pg-migrations/tree/master/example). As mentioned in the linked comment, if you have a recommendation of how to dynamically load the migration files (as Go files, not SQL files), I'd love to hear about it!

**Comment by ernsheong** [comment]
Sorry to duplicate an issue, so yes maybe we should just remove it then 👍

**Comment by robinjoseph08** [comment]
Sounds good, I'll put up a PR to get rid of that so it's not misleading.

And I agree, it is nice to keep it separate. I don't know if it works for your setup, but usually, I have a directory structure like this, and I'm happy enough having it all kept away in `cmd/migrations`:

```
.
├── cmd
│   ├── api
│   │   └── main.go
│   └── migrations
│       ├── 20200606231835_create_users_table.go
│       └── main.go
├── pkg
...
```

**Comment by ernsheong** [comment]
Thanks for working on this!
