### ISSUE TITLE
create uses wrong package name

### ISSUE THREAD

**Issue by sgoldenb** [robinjoseph08/go-pg-migrations#26]
Hi there,
i would like to have my migrations in a separate folder like so:

```
err := gpgm.Run(db, "migrations", os.Args)
```
Using the "create" command creates the migration in the right place but the package name is wrong. 
It should be the name of the folder but it is "main" instead.

**Comment by robinjoseph08** [comment]
Hey @sgoldenb, thanks for reaching out.

The reason it makes the package name `main` instead of something else (like the directory name) is because the main way this package is meant to be used is to have the package where your migrations live be an entrypoint (i.e. a package with a `main()` function that will eventually be compiled and run). So if you're outputting the generated files to `migrations`, then it's also expected for there to be a `migrations/main.go` file that actually runs the `Run()` function. The [`example` directory](https://github.com/robinjoseph08/go-pg-migrations/blob/master/example/main.go) shows this in action. And for Go packages to be the entrypoint and have a `main()` function, it needs to be in a `main` package.

Hope that clears things up! If not, feel free to ask any followups!
