### ISSUE TITLE
CreateTable assignment mismatch

### ISSUE THREAD

**Issue by jakebailey** [robinjoseph08/go-pg-migrations#9]
go-getting this repo produces a compiler error:

```
../../robinjoseph08/go-pg-migrations/setup.go:57:9: assignment mismatch: 2 variables but 1 values
```

go-pg/pg#957 changed the signature of `CreateTable` to omit the `Result` and only return an error, so `createTable` in `setup.go` should be changed to just return `orm.CreateTable(...)`.

**Comment by robinjoseph08** [comment]
Good catch! This repo is meant to be used as a library though (since the final binary needs to be built with the user's migration files), so I don't think I can just vendor it. That said, it looks like it was just `orm.CreateTable` that changed its function signature, but `*pg.DB.CreateTable` has always just returned `error`. I'll just change `createTable` in `setup.go` to accept a `*pg.DB` instead of `orm.DB` since I don't really utilize the fact that it's accepting the interface. That should make it work for the current and future versions of `pg`.

**Comment by robinjoseph08** [comment]
I just created v0.1.1 where this should be fixed! Thanks for letting me know!
